version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mentor'
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
